package:
  name: ros-noetic-aruco
  version: 3.1.3
source:
  git_url: https://github.com/pal-gbp/aruco_ros-release.git
  git_rev: release/noetic/aruco/3.1.3-1
  folder: ros-noetic-aruco/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 17
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - eigen
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.5 noetic
    - ros-noetic-catkin
    - ros-noetic-cv-bridge
  run:
    - eigen
    - python
    - ros-distro-mutex 0.5 noetic
    - ros-noetic-cv-bridge
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
